services:
  backend:
    container_name: kcal-ai-bot-backend
    image: ghcr.io/d3vv3/kcal-ai-bot/backend:latest
    restart: unless-stopped
    ports:
      - "${API_PORT:-8000}:80"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ${BACKEND_DATA:-./data}:/data


  redis:
    container_name: kcal-ai-bot-redis
    image: "redis:7-alpine"

  worker:
    container_name: kcal-ai-bot-worker
    image: ghcr.io/d3vv3/kcal-ai-bot/backend:latest
    restart: unless-stopped
    command: rq worker --url redis://redis:6379
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ${BACKEND_DATA:-./data}:/data

  bot:
    container_name: kcal-ai-bot-bot
    image: ghcr.io/d3vv3/kcal-ai-bot/bot:latest
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BACKEND_BASE_URL=http://backend
