services:
  backend:
    build: .
    ports:
      - "${API_PORT:-8000}:80"
    depends_on:
      - redis
    volumes:
      - .:/app
      - ${BACKEND_DATA:-./data}:/app/data
    environment:
      - REDIS_URL=redis://redis:6379
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    command: /start-reload.sh

  redis:
    image: "redis:7-alpine"

  worker:
    build: .
    command: rq worker --url redis://redis:6379
    depends_on:
      - redis
    volumes:
      - .:/app
      - ${BACKEND_DATA:-./data}:/app/data
    environment:
      - REDIS_URL=redis://redis:6379
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
